### ISSUE TITLE
ability to ignore certain error from being count into IncSendMessageFailureCount()

### ISSUE THREAD

**Issue by haitch** [Azure/go-shuttle#207]
i.e. any contextError that not related servicebus client/server.

https://github.com/Azure/go-shuttle/blob/d03264ed0c43c5770448c3b9b006245c32199cfd/v2/sender.go#L81-L92

My initial thought is to add a `ErrorFilter func(error)bool` on `type SenderOptions struct`, we can run any error through that filter, and only IncSendMessageFailureCount() if filter return false.

https://github.com/Azure/go-shuttle/blob/d03264ed0c43c5770448c3b9b006245c32199cfd/v2/sender.go#L35-L45

**Comment by imiller31** [comment]
@haitch I think the problem here is the ambiguity with where the context error originated from. In the current select block, it's impossible for us to know if the context has already been canceled or if the context timed out during `sbSender.SendMessage`

If we were to blanket filter all context errors, then open the problem of not having actionable metrics on if the SbSender is dead.
